import { VerifiersData } from "@/types";
import { ROUTES } from "./routes";

export const sidebarList = [
  {
    id: 1,
    sidebar: "Verifiers",
    link: ROUTES.USER.VERIFIERS,
    //   icon: <HomeIcon />,
  },
  {
    id: 2,
    sidebar: "Deals",
    link: ROUTES.USER.DEALS,
    //   icon: <UserManagementIcon />,
  },
  {
    id: 3,
    sidebar: "Transactions",
    link: ROUTES.USER.TRANSACTIONS,
    //   icon: <OrderManagementIcon />,
  },
];

export const verifierData: VerifiersData[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "+2348098765432",
    partner: "XYZ Corp.",
    location: "Lagos, Nigeria",
    status: "Active",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    phoneNumber: "+2348098765433",
    partner: "ABC Ltd.",
    location: "Abuja, Nigeria",
    status: "Deactivated",
  },
  {
    id: "3",
    firstName: "Mark",
    lastName: "Johnson",
    phoneNumber: "+2348098765434",
    partner: "DEF Industries",
    location: "Port Harcourt, Nigeria",
    status: "Awaiting approval",
  },
  {
    id: "4",
    firstName: "Mary",
    lastName: "Williams",
    phoneNumber: "+2348098765435",
    partner: "GHI Enterprises",
    location: "Benin City, Nigeria",
    status: "Active",
  },
  {
    id: "5",
    firstName: "James",
    lastName: "Brown",
    phoneNumber: "+2348098765436",
    partner: "JKL Solutions",
    location: "Ibadan, Nigeria",
    status: "Deactivated",
  },
  {
    id: "6",
    firstName: "Patricia",
    lastName: "Davis",
    phoneNumber: "+2348098765437",
    partner: "MNO Group",
    location: "Enugu, Nigeria",
    status: "Awaiting approval",
  },
  {
    id: "7",
    firstName: "David",
    lastName: "Miller",
    phoneNumber: "+2348098765438",
    partner: "PQR Ltd.",
    location: "Kano, Nigeria",
    status: "Active",
  },
  {
    id: "8",
    firstName: "Linda",
    lastName: "Wilson",
    phoneNumber: "+2348098765439",
    partner: "STU Enterprises",
    location: "Kaduna, Nigeria",
    status: "Deactivated",
  },
  {
    id: "9",
    firstName: "Michael",
    lastName: "Moore",
    phoneNumber: "+2348098765440",
    partner: "VWX Corporation",
    location: "Owerri, Nigeria",
    status: "Awaiting approval",
  },
  {
    id: "10",
    firstName: "Elizabeth",
    lastName: "Taylor",
    phoneNumber: "+2348098765441",
    partner: "YZ Ltd.",
    location: "Asaba, Nigeria",
    status: "Active",
  },
];
